### ISSUE TITLE
通识课的二维码可不可以找到资源地址，然后requests下载用python的Image模块打开再手动输入？

### ISSUE THREAD

**Issue by vindinqi** [Luxru/CQU-Course#1]

**Comment by Luxru** [comment]
这里有两个地址：
http:///jxgl.cqu.edu.cn/wsxk/ValidateCode.aspx
http://jxgl.cqu.edu.cn/sys/ValidateCode.aspx
其中第一个是通识课的验证码链接、第二个是登陆时候的验证码链接，对于验证码的提交我并没有去查看过（懒），所以可以自己尝试去实现一下哟
附赠一个检索通识课需要提交的表单数据以及提交的url
http://jxgl.cqu.edu.cn/wsxk/stu_xszx_rpt.aspx
 {
            'SelSpeciality': ,
            'sel_xq': '4',
            'chk_kyme': '1',
            'txt_yzm': '',
            'sel_lx': '4',
            'kclb3': '',
            'Submit': '%BC%EC%CB%F7',
            }

**Comment by Luxru** [comment]
@vindinqi 
已经在allCourse.py中添加了输入验证码的功能 
如果可以的话希望可以在下一次选课的时候进行debug😂
